In [1]:
from ScrapUtils import *
import json5

In [2]:
baseurl = 'https://www.bergzeit.ch/'
tag = 'products-list-page-preloader__links'

In [3]:
scraper = ScrapExecutor()
links = []
for page in range(1, 8):
    links.extend(scraper.execute(f'https://www.bergzeit.ch/schuhe/kletterschuhe/?p={page}&sortBy=ct',
                                 baseurl, tag))

In [4]:
a= scraper.execute(links, baseurl)

In [7]:
import pandas as pd

df = pd.DataFrame(a)
# 1. Explode lists into individual rows
#df_exploded = df.explode('availableSizes')

# 2. Flatten and generate mapper (or just map directly on the exploded column)
#a = df_exploded['availableSizes'].dropna().unique()
#mapper = convert_size(a)

# 3. Now .map() works because the column contains strings, not lists
#df_exploded['convertedSize'] = df_exploded['availableSizes'].map(mapper)

#df_exploded
df.to_csv(ScrapedData/kletterschuhe_raw

,shortDescription,longDescription,availableSizes,Geeignet für,Sportart,Kletteranspruch,Vorspannung,Downturn,Asymmetrie,Sohlentechnologie,...,Vibram®,Bergzeit Empfehlung,Nachhaltige Produktmerkmale (Details s. Digitaler Produktpass),Auszeichnungen,Passformangabe Hersteller,Produkteigenschaften,Größeninformation,Profiltiefe,Material,Schafthöhe
0,Komfortabler Kletterschuh mit intuitiver Passf...,Der HyperEZ wurde speziell für Klettereinsteig...,"[36, 36.5, 37, 37.5, 38, 38.5, 39, 39.5, 40, 4...","[Damen, Herren]",[Sportklettern],"[ambitionierte Kletterer, Klettereinsteiger]",[keine Vorspannung],[ohne Downturn],[wenig asymmetrisch],"[FriXion® (LaSportiva), wiederbesohlbar]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bequemer Damen-Kletterschuh mit Schnürung für ...,Der Women’s Momentum Lace von Black Diamond is...,"[US 7.5, US 7.5+, US 8, US 10]",[Damen],"[Bouldern, Sportklettern]",[ambitionierte Kletterer],[wenig Vorspannung],[ohne Downturn],[wenig asymmetrisch],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Durchdachter Kinder-Kletterschuh für optimales...,Die La Sportiva Gripit Kid sind durchdachte Kl...,"[24, 26, 28, 30, 32, 34, 36]",[Kinder],"[Bouldern, Sportklettern]",[Klettereinsteiger],[keine Vorspannung],[ohne Downturn],[wenig asymmetrisch],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Extrem sensibler, präziser und trotzdem komfor...",Diese Kletterschuhe wurden für Athleten entwic...,"[36, 36.5, 37, 37.5, 38, 38.5, 39, 39.5, 40, 4...","[Damen, Herren]","[Bouldern, Sportklettern]",[ambitionierte Kletterer],[mittlere Vorspannung],[mit Downturn],[stark asymmetrisch],[Vibram®],...,[XS Grip2],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Extrem langlebiger Einsteigerschuh mit gerader...,Die Session 4 Kletterschuhe von Red Chili sind...,"[UK 1, UK 1.5, UK 2, UK 2.5, UK 3, UK 3.5, UK ...","[Damen, Herren]","[Bouldern, Sportklettern]",[Klettereinsteiger],[keine Vorspannung],[ohne Downturn],[wenig asymmetrisch],NaN,...,NaN,[Wähle im Vergleich zu Deiner üblichen Straßen...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,Weicher Kletterschuh mit viel Feingefühl beim ...,"Der Iris von Ocun ist so konzipiert, dass er d...","[UK 3.5, UK 4]","[Damen, Herren]","[Bouldern, Sportklettern]",[ambitionierte Kletterer],[mittlere Vorspannung],[mit Downturn],[moderat asymmetrisch],NaN,...,NaN,NaN,[veganes Produkt (Herstellerangabe)],NaN,NaN,NaN,NaN,NaN,NaN,NaN
287,High-End Waffe aus der Black Diamond Schmiede ...,"Im dunklen Schatten verstecken, braucht sich d...",[US 7.5],"[Damen, Herren]","[Bouldern, Sportklettern]",[Kletterexperten],[starke Vorspannung],[mit Downturn],[stark asymmetrisch],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,Performanceorientierter Boulderschuh für moder...,Der Zenist Pro Kletterschuh von Evolv ist auf ...,"[UK 3, UK 3.5, UK 4, UK 4.5]","[Damen, Herren]","[Bouldern, Sportklettern]",[ambitionierte Kletterer],[mittlere Vorspannung],[mit Downturn],[moderat asymmetrisch],NaN,...,NaN,[+ 0 Profis: Bestelle die gleiche Größe wie De...,[veganes Produkt (Herstellerangabe)],NaN,[Low Volume],NaN,[fällt kleiner aus],NaN,NaN,NaN
289,Performanceorientierter Boulderschuh für moder...,Der Zenist Pro Kletterschuh von Evolv ist auf ...,"[UK 4, UK 4.5, UK 5, UK 5.5]","[Damen, Herren]","[Bouldern, Sportklettern]",[ambitionierte Kletterer],[mittlere Vorspannung],[mit Downturn],[moderat asymmetrisch],NaN,...,NaN,[+ 0 Profis: Bestelle die gleiche Größe wie De...,[veganes Produkt (Herstellerangabe)],NaN,[Medium Volume],NaN,[fällt kleiner aus],NaN,NaN,NaN
290,Sensibler Kletterschuh für modernes Bouldern u...,MIt dem Shaman Pro LV von Evolv kannst du dein...,"[UK 3, UK 3.5]","[Damen, Herren]","[Bouldern, Sportklettern]",[ambitionierte Kletterer],[mittlere Vorspannung],[mit Downturn],[stark asymmetrisch],NaN,...,NaN,[+ 0 Profis: Bestelle die gleiche Größe wie De...,[veganes Produkt (Herstellerangabe)],NaN,[Low Volume],NaN,[fällt kleiner aus],NaN,NaN,NaN

In [85]:
import numpy as np

def flatten_lists(df):
    res = []
    # .dropna() prevents errors on missing rows
    for sizes in df['availableSizes'].dropna():
        if isinstance(sizes, (list, np.ndarray)):
            for size in sizes:
                if size not in res:
                    res.append(size)
    return np.unique(res)

def convert_size(flat_list):
    res = {}
    for size in flat_list:
        if not isinstance(size, str):
            continue
        if 'US' in size:
            res[size] = np.round(float(size.replace('US ', '').replace(',','.').replace('+','').strip()), 1) + 32
        elif 'UK' in size:
            res[size] = np.round(float(size.replace('UK ', '').replace(',','.').strip()), 1) + 33
        elif '-' in size:
            res[size] = np.round(float(size.split('-')[0]), 1)
        elif 'EUI' in size:
            res[size] = np.round(float(size.replace('EUI ', '').replace(',', '')), 1)
        else:
            res[size] = np.round(float(size.replace(',', '')), 1)
    return res

a = flatten_lists(df)
mapper = convert_size(a)

# Apply the mapper to each item inside the lists safely
df['convertedSizes'] = df['availableSizes'].apply(
    lambda x: [mapper.get(size) for size in x] if isinstance(x, (list, np.ndarray)) else x
)

df

,shortDescription,longDescription,availableSizes,Geeignet für,Sportart,Kletteranspruch,Vorspannung,Downturn,Asymmetrie,Sohlentechnologie,...,Vibram®,Bergzeit Empfehlung,Auszeichnungen,Passformangabe Hersteller,Nachhaltige Produktmerkmale (Details s. Digitaler Produktpass),Größeninformation,Profiltiefe,Material,Schafthöhe,convertedSizes
0,Komfortabler Kletterschuh mit intuitiver Passf...,Der HyperEZ wurde speziell für Klettereinsteig...,"[36, 36.5, 37, 37.5, 38, 38.5, 39, 39,5, 40, 4...","[Damen, Herren]",[Sportklettern],"[ambitionierte Kletterer, Klettereinsteiger]",[keine Vorspannung],[ohne Downturn],[wenig asymmetrisch],"[FriXion® (LaSportiva), wiederbesohlbar]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[36.0, 36.5, 37.0, 37.5, 38.0, 38.5, 39.0, 395..."
1,Bequemer Damen-Kletterschuh mit Schnürung für ...,Der Women’s Momentum Lace von Black Diamond is...,"[US 7,5, US 7.5+, US 8, US 10]",[Damen],"[Bouldern, Sportklettern]",[ambitionierte Kletterer],[wenig Vorspannung],[ohne Downturn],[wenig asymmetrisch],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[39.5, 39.5, 40.0, 42.0]"
2,"Leistungsstarker, Kletterschuh mit mittlerem V...",Der EVOLV Shaman Trance ist ein Performance-Kl...,"[38, 38.5, 39, 39,5, 40, 40.5, 41, 41.5, 42, 4...","[Damen, Herren]","[Bouldern, Sportklettern]",[Kletterexperten],[mittlere Vorspannung],[mit Downturn],[moderat asymmetrisch],[wiederbesohlbar],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[38.0, 38.5, 39.0, 395.0, 40.0, 40.5, 41.0, 41..."
3,Durchdachter Kinder-Kletterschuh für optimales...,Die La Sportiva Gripit Kid sind durchdachte Kl...,"[24, 26, 28, 30, 32, 34, 36]",[Kinder],"[Bouldern, Sportklettern]",[Klettereinsteiger],[keine Vorspannung],[ohne Downturn],[wenig asymmetrisch],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[24.0, 26.0, 28.0, 30.0, 32.0, 34.0, 36.0]"
4,"Extrem sensibler, präziser und trotzdem komfor...",Diese Kletterschuhe wurden für Athleten entwic...,"[36, 36.5, 37, 37.5, 38, 38.5, 39, 39,5, 40, 4...","[Damen, Herren]","[Bouldern, Sportklettern]",[ambitionierte Kletterer],[mittlere Vorspannung],[mit Downturn],[stark asymmetrisch],[Vibram®],...,[XS Grip2],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[36.0, 36.5, 37.0, 37.5, 38.0, 38.5, 39.0, 395..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,Performanceorientierter Boulderschuh für moder...,Der Zenist Pro Kletterschuh von Evolv ist auf ...,"[UK 4, UK 4.5, UK 5, UK 5.5, UK 6]","[Damen, Herren]","[Bouldern, Sportklettern]",[ambitionierte Kletterer],[mittlere Vorspannung],[mit Downturn],[moderat asymmetrisch],NaN,...,NaN,[+ 0 Profis: Bestelle die gleiche Größe wie De...,NaN,[Medium Volume],[veganes Produkt (Herstellerangabe)],[fällt kleiner aus],NaN,NaN,NaN,"[37.0, 37.5, 38.0, 38.5, 39.0]"
287,High-End Waffe aus der Black Diamond Schmiede ...,"Im dunklen Schatten verstecken, braucht sich d...","[US 7,5, US 8,5]","[Damen, Herren]","[Bouldern, Sportklettern]",[Kletterexperten],[starke Vorspannung],[mit Downturn],[stark asymmetrisch],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[39.5, 40.5]"
288,Performanceorientierter Boulderschuh für moder...,Der Zenist Pro Kletterschuh von Evolv ist auf ...,"[UK 3, UK 3.5, UK 4, UK 4.5]","[Damen, Herren]","[Bouldern, Sportklettern]",[ambitionierte Kletterer],[mittlere Vorspannung],[mit Downturn],[moderat asymmetrisch],NaN,...,NaN,[+ 0 Profis: Bestelle die gleiche Größe wie De...,NaN,[Low Volume],[veganes Produkt (Herstellerangabe)],[fällt kleiner aus],NaN,NaN,NaN,"[36.0, 36.5, 37.0, 37.5]"
289,Extra für das Indoorklettern entwickelter Schu...,Der Black Opium Kletterschuhe von eb ist für a...,[35.5],[Damen],"[Bouldern, Sportklettern]","[ambitionierte Kletterer, Kletterexperten]",[wenig Vorspannung],[mit Downturn],[stark asymmetrisch],NaN,...,NaN,NaN,NaN,NaN,[veganes Produkt (Herstellerangabe)],NaN,NaN,NaN,NaN,[35.5]
290,Sensibler Kletterschuh für modernes Bouldern u...,MIt dem Shaman Pro LV von Evolv kannst du dein...,"[UK 3, UK 3.5]","[Damen, Herren]","[Bouldern, Sportklettern]",[ambitionierte Kletterer],[mittlere Vorspannung],[mit Downturn],[stark asymmetrisch],NaN,...,NaN,[+ 0 Profis: Bestelle die gleiche Größe wie De...,NaN,[Low Volume],[veganes Produkt (Herstellerangabe)],[fällt kleiner aus],NaN,NaN,NaN,"[36.0, 36.5]"

In [59]:
# 1. Find all columns where at least one entry is a list
list_cols = [col for col in df.columns if df[col].apply(lambda x: isinstance(x, list)).any()]

# 2. Loop through those columns and expand them
for col in list_cols:
    # .apply(pd.Series) splits each list element into its own column
    expanded = df[col].apply(pd.Series)
    
    # Rename the new columns to avoid naming collisions (e.g., features_0, features_1)
    expanded = expanded.rename(columns=lambda x: f"{col}_{x}")
    
    # Drop the original list column and merge the new columns
    df = pd.concat([df.drop(columns=[col]), expanded], axis=1)

,shortDescription,longDescription,availableSizes_0,availableSizes_1,availableSizes_2,availableSizes_3,availableSizes_4,availableSizes_5,availableSizes_6,availableSizes_7,...,Auszeichnungen_0,Passformangabe Hersteller_0,Nachhaltige Produktmerkmale (Details s. Digitaler Produktpass)_0,Nachhaltige Produktmerkmale (Details s. Digitaler Produktpass)_1,Größeninformation_0,Profiltiefe_0,Material_0,Material_1,Material_2,Schafthöhe_0
0,Komfortabler Kletterschuh mit intuitiver Passf...,Der HyperEZ wurde speziell für Klettereinsteig...,36,36.5,37,37.5,38,38.5,39,"39,5",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bequemer Damen-Kletterschuh mit Schnürung für ...,Der Women’s Momentum Lace von Black Diamond is...,"US 7,5",US 7.5+,US 8,US 10,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Leistungsstarker, Kletterschuh mit mittlerem V...",Der EVOLV Shaman Trance ist ein Performance-Kl...,38,38.5,39,"39,5",40,40.5,41,41.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Durchdachter Kinder-Kletterschuh für optimales...,Die La Sportiva Gripit Kid sind durchdachte Kl...,24,26,28,30,32,34,36,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Extrem sensibler, präziser und trotzdem komfor...",Diese Kletterschuhe wurden für Athleten entwic...,36,36.5,37,37.5,38,38.5,39,"39,5",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,Performanceorientierter Boulderschuh für moder...,Der Zenist Pro Kletterschuh von Evolv ist auf ...,UK 4,UK 4.5,UK 5,UK 5.5,UK 6,NaN,NaN,NaN,...,NaN,Medium Volume,veganes Produkt (Herstellerangabe),NaN,fällt kleiner aus,NaN,NaN,NaN,NaN,NaN
287,High-End Waffe aus der Black Diamond Schmiede ...,"Im dunklen Schatten verstecken, braucht sich d...","US 7,5","US 8,5",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,Performanceorientierter Boulderschuh für moder...,Der Zenist Pro Kletterschuh von Evolv ist auf ...,UK 3,UK 3.5,UK 4,UK 4.5,NaN,NaN,NaN,NaN,...,NaN,Low Volume,veganes Produkt (Herstellerangabe),NaN,fällt kleiner aus,NaN,NaN,NaN,NaN,NaN
289,Extra für das Indoorklettern entwickelter Schu...,Der Black Opium Kletterschuhe von eb ist für a...,35.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,veganes Produkt (Herstellerangabe),NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,Sensibler Kletterschuh für modernes Bouldern u...,MIt dem Shaman Pro LV von Evolv kannst du dein...,UK 3,UK 3.5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Low Volume,veganes Produkt (Herstellerangabe),NaN,fällt kleiner aus,NaN,NaN,NaN,NaN,NaN

In [60]:
df.columns

Index(['shortDescription', 'longDescription', 'availableSizes_0',
       'availableSizes_1', 'availableSizes_2', 'availableSizes_3',
       'availableSizes_4', 'availableSizes_5', 'availableSizes_6',
       'availableSizes_7', 'availableSizes_8', 'availableSizes_9',
       'availableSizes_10', 'availableSizes_11', 'availableSizes_12',
       'availableSizes_13', 'availableSizes_14', 'availableSizes_15',
       'availableSizes_16', 'availableSizes_17', 'availableSizes_18',
       'availableSizes_19', 'availableSizes_20', 'availableSizes_21',
       'availableSizes_22', 'availableSizes_23', 'availableSizes_24',
       'availableSizes_25', 'availableSizes_26', 'availableSizes_27',
       'availableSizes_28', 'availableSizes_29', 'availableSizes_30',
       'Geeignet für_0', 'Geeignet für_1', 'Sportart_0', 'Sportart_1',
       'Sportart_2', 'Kletteranspruch_0', 'Kletteranspruch_1', 'Vorspannung_0',
       'Downturn_0', 'Asymmetrie_0', 'Sohlentechnologie_0',
       'Sohlentechnologie_1', 'Schuhverschluss_0', 'Schuhverschluss_1',
       'Fußbreite_0', 'Passform_0', 'Schuhtechnologie_0',
       'Schuh-Außenmaterial_0', 'Schuh-Außenmaterial_1',
       'Schuh-Außenmaterial_2', 'Schuh-Außenmaterial_3', 'Schuhsohle_0',
       'Schuhsohle_1', 'Schuhsohle_2', 'Schuhsohle_3', 'Schuhsohle_4',
       'Schuh-Innenmaterial_0', 'Schuh-Innenmaterial_1',
       'Schuh-Innenmaterial_2', 'Schuh-Innenmaterial_3',
       'weitere Technologie_0', 'weitere Technologie_1',
       'weitere Technologie_2', 'weitere Technologie_3',
       'weitere Technologie_4', 'weitere Technologie_5', 'Made in_0',
       'Sohlenhärte_0', 'Referenzgewicht pro Paar_0', 'Produkteigenschaften_0',
       'Produkteigenschaften_1', 'Fußform_0', 'Fußform_1', 'Fußform_2',
       'Vibram®_0', 'Bergzeit Empfehlung_0', 'Bergzeit Empfehlung_1',
       'Bergzeit Empfehlung_2', 'Auszeichnungen_0',
       'Passformangabe Hersteller_0',
       'Nachhaltige Produktmerkmale (Details s. Digitaler Produktpass)_0',
       'Nachhaltige Produktmerkmale (Details s. Digitaler Produktpass)_1',
       'Größeninformation_0', 'Profiltiefe_0', 'Material_0', 'Material_1',
       'Material_2', 'Schafthöhe_0'],
      dtype='object')

In [61]:
import numpy as np

def convert_size(df):
    res = {}
    for size in df['availableSizes'].unique():
        if 'US' in size:
            res[size] = np.round(float(size.replace('US ', '').replace(',','.').strip()), 1) + 32
        elif 'UK' in size:
            res[size] = np.round(float(size.replace('UK ', '').replace(',','.').strip()), 1) + 33
        elif '-' in size:
            res[size] = np.round(float(size.split('-')[0]), 1)
        else:
            res[size] = np.round(float(size), 1)
    return res

In [62]:
pp = convert_size(df)

In [63]:
pp

{'36': np.float64(36.0),
 'US 7,5': np.float64(39.5),
 '38': np.float64(38.0),
 '24': np.float64(24.0),
 '28': np.float64(28.0),
 'UK 1': np.float64(34.0),
 'UK 3': np.float64(36.0),
 '35': np.float64(35.0),
 '29': np.float64(29.0),
 '37.5': np.float64(37.5),
 '33': np.float64(33.0),
 'US 6,5': np.float64(38.5),
 '39': np.float64(39.0),
 '26': np.float64(26.0),
 '34': np.float64(34.0),
 '37': np.float64(37.0),
 '36.5': np.float64(36.5),
 '35.5': np.float64(35.5),
 'UK 5': np.float64(38.0),
 'UK 4': np.float64(37.0),
 'UK 2.5': np.float64(35.5),
 '27-28': np.float64(27.0),
 '30': np.float64(30.0),
 'UK 3.5': np.float64(36.5),
 'UK 5.5': np.float64(38.5),
 '34.5': np.float64(34.5),
 'US 4': np.float64(36.0),
 'UK 6': np.float64(39.0),
 'US 4.5': np.float64(36.5),
 'UK 4.5': np.float64(37.5),
 'US 5': np.float64(37.0),
 '32': np.float64(32.0),
 'US 3.5': np.float64(35.5),
 'UK 12': np.float64(45.0),
 'US 3': np.float64(35.0),
 'US 5.5': np.float64(37.5),
 'UK 11.5': np.float64(44.5),
 '24-25': np.float64(24.0),
 '44': np.float64(44.0)}